[package]
name = "unity-mirror-macro"
version = "0.1.0"
edition = "2024"

[lib]
proc-macro = true

[dependencies]
syn = { version = "2.0.98", features = ["full"] }
quote = { version = "1.0.38" }
proc-macro2 = { version = "1.0.93" }
rand = { version = "0.9.1" }
