[package]
name = "unity-mirror-rs"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "Unity Mirror Networking Server Only Rust"
homepage = "https://unity-mirror-rs.github.io"
documentation = "https://unity-mirror-rs.github.io/doc/"
repository = "https://github.com/xintujing/unity-mirror-rs"
readme = "README.md"

exclude = []

[dependencies]