[package]
name = "unity-mirror-rs"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = ""
homepage = ""
documentation = ""
repository = ""
readme = "README.md"

exclude = []

[dependencies]
